/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashmap.repeated.word;

import java.util.HashMap;
import java.util.Locale;
import java.util.Map;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static  String repeatedWord(String s){
        Map<String,String> hashMap = new HashMap<>();
        s = s.replace(",","");
        String[] words = s.split(" ");
        for (String word : words){
            word = word.toLowerCase();
            if(hashMap.containsKey(word))
                return word;
            else hashMap.put(word,word);
        }
        return null;
    }
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        System.out.println(repeatedWord("\"It was a queer, sultry summer, the summer they electrocuted the Rosenbergs, and I didn’t know what I was doing in New York...\""));

    }
}
