/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }


    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        LinkedList<Integer> linkedList = new LinkedList<Integer>();
        linkedList.inset(1);
        linkedList.inset(4);
        linkedList.inset(10);
        linkedList.inset(3);
        linkedList.inset(2);
        linkedList.inset(11);
        System.out.println( linkedList.toString());
        System.out.println( linkedList.includes(10));
        System.out.println( linkedList.includes(6));


    }
}
