/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Graph graph = new Graph();
        graph.addNode("1");
        graph.addNode("2");
        graph.addNode("3");
        graph.addNode("4");

        graph.addEdge("1", "2");
        graph.addEdge("2", "1");
        graph.addEdge("2", "3");
        graph.addEdge("4", "2");
        graph.addEdge("4", "3");

        System.out.println(graph);
        System.out.println(graph.getNodes());
        System.out.println(graph.getNeighbors("1"));
        System.out.println(graph.size());
    }
}
