/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quick.sort;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        int[] arr = {3,8,1,9,5};
        int n = arr.length;
        quickSort(arr, 0, n - 1);
        printMyArray(arr,n);
    }

    static void swapItem(int[] arr, int i, int j)
    {
        int temp = arr[i];
        arr[i] = arr[j];
        arr[j] = temp;
    }


    static int partition(int[] arr, int low, int high)
    {
        int pivot = arr[high];
        int i = (low - 1);

        for(int j = low; j <= high - 1; j++)
        {
            if (arr[j] < pivot)
            {
                i++;
                swapItem(arr, i, j);
            }
        }
        swapItem(arr, i + 1, high);
        return (i + 1);
    }

    static int[] quickSort(int[] arr, int low, int high)
    {
        if (low < high)
        {
            int p = partition(arr, low, high);
            quickSort(arr, low, p - 1);
            quickSort(arr, p + 1, high);
        }
        return arr;
    }

    static void printMyArray(int[] arr, int size)
    {
        for(int i = 0; i < size; i++)
            System.out.print(arr[i] + " ");
             System.out.println();
    }

}
