/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package merge.sort;

import java.util.Arrays;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        int[] arr = {6, 4, 9, 1, 2};
        System.out.println(Arrays.toString(mergeSort(arr)));
    }

    public static int[] mergeSort(int[] arr) {
        int n = arr.length;
        if (n > 1) {
            int mid = n / 2;
            int[] l = new int[mid];
            int[] r = new int[n - mid];

            for (int i = 0; i < l.length; ++i) {
                l[i] = arr[i];
            }
            for (int j = 0; j < r.length; ++j) {
                r[j] = arr[j + mid];
            }
            mergeSort(l);
            mergeSort(r);
            merge(l, r, arr);
        }
        return arr;
    }

    public static void merge(int[] l, int[] r, int[] arr) {

        int i = 0, j = 0, k = 0;
        while (i < l.length && j < r.length) {
            if (l[i] <= r[j]) {
                arr[k] = l[i];
                i++;
            } else {
                arr[k] = r[j];
                j++;
            }
            k++;
        }
        if (i == l.length) {
            for (int I = j; I < r.length; I++) {
                arr[k++] = r[I];

            }
        } else {
            for (int m = i; m < l.length; m++) {
                arr[k++] = l[m];
            }
        }
    }
}