/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trees;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        BinaryTree<Integer> newTree = new BinaryTree<>();

        Node<Integer> node1 = new Node<>(3);
        Node<Integer> node2 = new Node<>(5);
        Node<Integer> node3 = new Node<>(9, node1, node2);
        Node<Integer> node4 = new Node<>(1);
        Node<Integer> node5 = new Node<>(7, node4, null);
        Node<Integer> tree = new Node<>(4, node3, node5);





//        BinarySearchTree binarySearchTree = new BinarySearchTree ();
//        binarySearchTree.insert(5);
//        binarySearchTree.insert(3);
//        binarySearchTree.insert(11);
//        binarySearchTree.insert(3);
//        binarySearchTree.insert(10);
//        binarySearchTree.insert(9);
//
//
//        System.out.println(binarySearchTree.breadthFirst(binarySearchTree));

    }
}
