/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph2;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

      Graph graph = new Graph();

        graph.addNode("1");
        graph.addNode("2");
        graph.addNode("7");
        graph.addNode("5");
        graph.addEdge("1", "2", 30);
        graph.addEdge("5", "1", 50);
        graph.addEdge("7", "5", 100);


        String[] trip1 = {"1", "2"};
        String[] trip2 = {"1", "5", "7"};
        String[] trip3 = {"1", "2", "5"};


//        System.out.println(graph);
//        System.out.println(graph.getNodes());
//        System.out.println(graph.getNeighbors("1"));
//        System.out.println(graph.size());

        System.out.println(graph.businessTrip("1",trip1));
        System.out.println(graph.businessTrip("1",trip2));
        System.out.println(graph.businessTrip("1",trip3));


    }
}
