/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package merge.sort;

import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void  mergeSortEmpty(){
        int[] arr = {};
        assertEquals(arr,App.mergeSort(arr));
    }

    @Test void  mergeSortArr(){
        int[] arr = {10,5,8,1};
        assertEquals("[1, 5, 8, 10]", Arrays.toString(App.mergeSort(arr)));
    }

    @Test void  ReverseSorted(){
        int[] arr = {20,18,12,8,5,-2};
        assertEquals("[-2, 5, 8, 12, 18, 20]", Arrays.toString(App.mergeSort(arr)));
    }
    @Test void  FewUniques(){
        int[] arr = {5,12,7,5,5,7};
        assertEquals("[5, 5, 5, 7, 7, 12]", Arrays.toString(App.mergeSort(arr)));
    }
    @Test void  NearlySorted(){
        int[] arr = {2,3,5,7,13,11};
        assertEquals("[2, 3, 5, 7, 11, 13]", Arrays.toString(App.mergeSort(arr)));
    }


}
