/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    public void addNode(){

        Graph graph = new Graph();

        graph.addNode("1");
        graph.addNode("2");
        graph.addNode("3");
        assertNotNull(graph.getNodes());
        assertEquals(3, graph.size());
    }

    @Test public void addEdge(){

        Graph graph = new Graph();
        graph.addNode("1");
        graph.addNode("2");
        graph.addEdge("1", "2");

        assertEquals("{1=[2], 2=[1]}", graph.toString());
    }

    @Test public void NodeNeighbors(){

        Graph graph = new Graph();
        graph.addNode("1");
        graph.addNode("2");
        graph.addNode("3");
        graph.addEdge("1", "2");
        graph.addEdge("2", "1");
        graph.addEdge("3", "2");
        assertEquals("[2, 2]", graph.getNeighbors("1").toString());


    }

    @Test public void oneNodeAndOneEdge(){

        Graph graph = new Graph();
        graph.addNode("1");
        graph.addEdge("1","1");
        assertEquals("{1=[1]}", graph.toString());
    }
}
