/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package insertion.sort;

import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void insertionSortEmpty(){
        int[] arr={};
        assertArrayEquals(arr,App.sort(arr));
    }

    @Test void insertionSort(){
        int[] arr={10,1,5,3,8};
        assertEquals("[1, 3, 5, 8, 10]", Arrays.toString(App.sort(arr)));
    }


    @Test void insertionSortReverseSorted(){
        int[] arr={12,10,5,3,-2};
        assertEquals("[-2, 3, 5, 10, 12]", Arrays.toString(App.sort(arr)));
    }

    @Test void insertionSortFewUniques(){
        int[] arr={5,12,7,5,5,7};
        assertEquals("[5, 5, 5, 7, 7, 12]", Arrays.toString(App.sort(arr)));    }

    @Test void insertionSortNearlySorted(){
        int[] arr={2,3,5,7,13,11};
        assertEquals("[2, 3, 5, 7, 11, 13]", Arrays.toString(App.sort(arr)));    }


}
